version: "3.9"

services:
  database:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentxps
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    container_name: rentx
    build: .
    restart: always
    command: npm run dev
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
